# Dependencies
markdown:         redcarpet
highlighter:      rouge

gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title : Shiftkey Labs
tagline: 'A pre-incubator program with a relentless focus on technology.'

url:              http://shiftkeylabs.github.io/
baseurl:          /


author :
  name: 'ShiftKey Labs'
  email : grant@shiftkeylabs.ca
  github : shiftkeylabs
  twitter : shiftkeylabs

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shiftkeylabs/
